### PR TITLE
Support setting config values in a .env file

### PR DESCRIPTION
**Pull request by philipsd6**
This is useful for me, as in development mode I can consolidate all my runtime variables in one .env file, including the MSAL config.

### CODE REVIEW

**Comment by philipsd6** [comment]
I just noticed you removed this in daf091d:
```python
-    class Config:
-        env_file = "fastapi_msal.env"
```
&hellip;any reason why? In any case, I'd prefer to support the standard `.env` file.

**Comment by yuenherny** [comment]
@dudil In my case, I resorted to `auth.cfg` because I have Python paths as environment variables listed in `.env` file (VS Code linter couldn't lint properly). Wouldn't want to track that on VCS, right?

**Comment by dudil** [comment]
@philipsd6 & @yuenherny - I believe that Pydantic had since changed their way of reading values from .env files.
Are you able to verify that on your end?
This would be very much appreciated 🙏

**Comment by yuenherny** [comment]
> @philipsd6 & @yuenherny - I believe that Pydantic had since changed their way of reading values from .env files. Are you able to verify that on your end? This would be very much appreciated 🙏

Hi @dudil , I believe so. Pydantic moved from declaring a `Config` class in V1 to using `ConfigDict` in V2. Pydantic V2 support for `.env` is available [here](https://docs.pydantic.dev/2.0/usage/pydantic_settings/#dotenv-env-support).

Apologies for the late reply. Was occupied for the past few months.

**Comment by dudil** [comment]
Hi @yuenherny,
Thank you for that. This was already handled with the migration to Pydantic V2.

🙏

**Pull request closed without merging**
